# docker-compose のバージョン
version: '3'

# 各コンテナの情報
services:

  # postgres サービス
  db:
    # コンテナの名前
    container_name: workout_note_db
    # Dockerfile のディレクトリパス
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    # postgres 設定
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db  

  # golang アプリケーション
  app:
    container_name: workout_note_app
    # postgres をビルドした後に app をビルド
    depends_on:
      - db
    # Dockerfile を指定
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    tty: true
    # GOPATHを指定
    environment:
      - GOPATH=/go
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - ./go:/go/src/app/go/
    # docker-compose run 実行時に実行されるコマンド
    command: go run main.go
    ports:
      - 8080:8080
  
  # nginx プロキシサーバー    
  nginx:
    container_name: workout_note_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app

  # cache サービス
  cache:
    container_name: workout_note_cache
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./redis.conf:/etc/redis.conf"